version: "3"
services:
  app:
    build: .
    image: lorxiong/flask-mongo-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
